[2024-08-01T17:19:30.951042+02:00] request.INFO: Matched route "create_user". {"route":"create_user","route_parameters":{"_route":"create_user","_controller":"App\\Controller\\UserController::createUser"},"request_uri":"http://localhost/users","method":"POST"} []
[2024-08-01T17:19:31.029063+02:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2024-08-01T17:19:31.159005+02:00] doctrine.INFO: Connecting with parameters array{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"symf_test","charset":"utf8mb4"} {"params":{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"symf_test","charset":"utf8mb4"}} []
[2024-08-01T17:19:31.170940+02:00] doctrine.INFO: Connecting with parameters array{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"charset":"utf8mb4"} {"params":{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"charset":"utf8mb4"}} []
[2024-08-01T17:19:31.177877+02:00] doctrine.INFO: Disconnecting [] []
[2024-08-01T17:19:31.185571+02:00] doctrine.INFO: Connecting with parameters array{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"symf_test","charset":"utf8mb4"} {"params":{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"symf_test","charset":"utf8mb4"}} []
[2024-08-01T17:19:31.257130+02:00] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ConnectionException: "An exception occurred in the driver: SQLSTATE[HY000] [1049] Unknown database 'symf_test'" at C:\Users\Arman Saleem\Desktop\symfony\users-service\vendor\doctrine\dbal\src\Driver\API\MySQL\ExceptionConverter.php line 101 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 1049): An exception occurred in the driver: SQLSTATE[HY000] [1049] Unknown database 'symf_test' at C:\\Users\\Arman Saleem\\Desktop\\symfony\\users-service\\vendor\\doctrine\\dbal\\src\\Driver\\API\\MySQL\\ExceptionConverter.php:101)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'symf_test' at C:\\Users\\Arman Saleem\\Desktop\\symfony\\users-service\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Exception.php:28)\n[previous exception] [object] (PDOException(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'symf_test' at C:\\Users\\Arman Saleem\\Desktop\\symfony\\users-service\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\MySQL\\Driver.php:33)"} []
[2024-08-01T17:26:06.122015+02:00] request.INFO: Matched route "create_user". {"route":"create_user","route_parameters":{"_route":"create_user","_controller":"App\\Controller\\UserController::createUser"},"request_uri":"http://localhost/users","method":"POST"} []
[2024-08-01T17:26:06.261426+02:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2024-08-01T17:26:06.441738+02:00] doctrine.INFO: Connecting with parameters array{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_sqlite","host":"localhost","port":null,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":[],"memory":true,"charset":"utf8"} {"params":{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_sqlite","host":"localhost","port":null,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":[],"memory":true,"charset":"utf8"}} []
[2024-08-01T17:26:06.858108+02:00] doctrine.DEBUG: Beginning transaction [] []
[2024-08-01T17:26:06.922755+02:00] doctrine.DEBUG: Rolling back transaction [] []
[2024-08-01T17:26:07.023326+02:00] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\TableNotFoundException: "An exception occurred while executing a query: SQLSTATE[HY000]: General error: 1 no such table: user" at C:\Users\Arman Saleem\Desktop\symfony\users-service\vendor\doctrine\dbal\src\Driver\API\SQLite\ExceptionConverter.php line 52 {"exception":"[object] (Doctrine\\DBAL\\Exception\\TableNotFoundException(code: 1): An exception occurred while executing a query: SQLSTATE[HY000]: General error: 1 no such table: user at C:\\Users\\Arman Saleem\\Desktop\\symfony\\users-service\\vendor\\doctrine\\dbal\\src\\Driver\\API\\SQLite\\ExceptionConverter.php:52)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1): SQLSTATE[HY000]: General error: 1 no such table: user at C:\\Users\\Arman Saleem\\Desktop\\symfony\\users-service\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Exception.php:28)\n[previous exception] [object] (PDOException(code: HY000): SQLSTATE[HY000]: General error: 1 no such table: user at C:\\Users\\Arman Saleem\\Desktop\\symfony\\users-service\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Connection.php:59)"} []
[2024-08-01T17:27:07.338897+02:00] request.INFO: Matched route "create_user". {"route":"create_user","route_parameters":{"_route":"create_user","_controller":"App\\Controller\\UserController::createUser"},"request_uri":"http://localhost/users","method":"POST"} []
[2024-08-01T17:27:07.393865+02:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2024-08-01T17:27:07.444720+02:00] doctrine.INFO: Connecting with parameters array{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_sqlite","host":"localhost","port":null,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":[],"memory":true,"charset":"utf8"} {"params":{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_sqlite","host":"localhost","port":null,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":[],"memory":true,"charset":"utf8"}} []
[2024-08-01T17:27:07.474114+02:00] doctrine.DEBUG: Beginning transaction [] []
[2024-08-01T17:27:07.527283+02:00] doctrine.DEBUG: Rolling back transaction [] []
[2024-08-01T17:27:07.593055+02:00] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\TableNotFoundException: "An exception occurred while executing a query: SQLSTATE[HY000]: General error: 1 no such table: user" at C:\Users\Arman Saleem\Desktop\symfony\users-service\vendor\doctrine\dbal\src\Driver\API\SQLite\ExceptionConverter.php line 52 {"exception":"[object] (Doctrine\\DBAL\\Exception\\TableNotFoundException(code: 1): An exception occurred while executing a query: SQLSTATE[HY000]: General error: 1 no such table: user at C:\\Users\\Arman Saleem\\Desktop\\symfony\\users-service\\vendor\\doctrine\\dbal\\src\\Driver\\API\\SQLite\\ExceptionConverter.php:52)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1): SQLSTATE[HY000]: General error: 1 no such table: user at C:\\Users\\Arman Saleem\\Desktop\\symfony\\users-service\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Exception.php:28)\n[previous exception] [object] (PDOException(code: HY000): SQLSTATE[HY000]: General error: 1 no such table: user at C:\\Users\\Arman Saleem\\Desktop\\symfony\\users-service\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Connection.php:59)"} []
[2024-08-01T17:28:14.159456+02:00] request.INFO: Matched route "create_user". {"route":"create_user","route_parameters":{"_route":"create_user","_controller":"App\\Controller\\UserController::createUser"},"request_uri":"http://localhost/users","method":"POST"} []
[2024-08-01T17:28:14.290608+02:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2024-08-01T17:28:14.424809+02:00] doctrine.INFO: Connecting with parameters array{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"symf_test","charset":"utf8mb4"} {"params":{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"symf_test","charset":"utf8mb4"}} []
[2024-08-01T17:28:14.480132+02:00] doctrine.INFO: Connecting with parameters array{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"charset":"utf8mb4"} {"params":{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"charset":"utf8mb4"}} []
[2024-08-01T17:28:14.486328+02:00] doctrine.INFO: Disconnecting [] []
[2024-08-01T17:28:14.494779+02:00] doctrine.INFO: Connecting with parameters array{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"symf_test","charset":"utf8mb4"} {"params":{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"symf_test","charset":"utf8mb4"}} []
[2024-08-01T17:28:14.589713+02:00] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ConnectionException: "An exception occurred in the driver: SQLSTATE[HY000] [1049] Unknown database 'symf_test'" at C:\Users\Arman Saleem\Desktop\symfony\users-service\vendor\doctrine\dbal\src\Driver\API\MySQL\ExceptionConverter.php line 101 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 1049): An exception occurred in the driver: SQLSTATE[HY000] [1049] Unknown database 'symf_test' at C:\\Users\\Arman Saleem\\Desktop\\symfony\\users-service\\vendor\\doctrine\\dbal\\src\\Driver\\API\\MySQL\\ExceptionConverter.php:101)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'symf_test' at C:\\Users\\Arman Saleem\\Desktop\\symfony\\users-service\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Exception.php:28)\n[previous exception] [object] (PDOException(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'symf_test' at C:\\Users\\Arman Saleem\\Desktop\\symfony\\users-service\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\MySQL\\Driver.php:33)"} []
[2024-08-01T17:30:32.934555+02:00] request.INFO: Matched route "create_user". {"route":"create_user","route_parameters":{"_route":"create_user","_controller":"App\\Controller\\UserController::createUser"},"request_uri":"http://localhost/users","method":"POST"} []
[2024-08-01T17:30:32.970800+02:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2024-08-01T17:30:33.002335+02:00] doctrine.INFO: Connecting with parameters array{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"symf_test","charset":"utf8mb4"} {"params":{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"symf_test","charset":"utf8mb4"}} []
[2024-08-01T17:30:33.010683+02:00] doctrine.INFO: Connecting with parameters array{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"charset":"utf8mb4"} {"params":{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"charset":"utf8mb4"}} []
[2024-08-01T17:30:33.016852+02:00] doctrine.INFO: Disconnecting [] []
[2024-08-01T17:30:33.025023+02:00] doctrine.INFO: Connecting with parameters array{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"symf_test","charset":"utf8mb4"} {"params":{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"symf_test","charset":"utf8mb4"}} []
[2024-08-01T17:30:33.071596+02:00] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ConnectionException: "An exception occurred in the driver: SQLSTATE[HY000] [1049] Unknown database 'symf_test'" at C:\Users\Arman Saleem\Desktop\symfony\users-service\vendor\doctrine\dbal\src\Driver\API\MySQL\ExceptionConverter.php line 101 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 1049): An exception occurred in the driver: SQLSTATE[HY000] [1049] Unknown database 'symf_test' at C:\\Users\\Arman Saleem\\Desktop\\symfony\\users-service\\vendor\\doctrine\\dbal\\src\\Driver\\API\\MySQL\\ExceptionConverter.php:101)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'symf_test' at C:\\Users\\Arman Saleem\\Desktop\\symfony\\users-service\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Exception.php:28)\n[previous exception] [object] (PDOException(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'symf_test' at C:\\Users\\Arman Saleem\\Desktop\\symfony\\users-service\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\MySQL\\Driver.php:33)"} []
[2024-08-01T17:31:34.620086+02:00] request.INFO: Matched route "create_user". {"route":"create_user","route_parameters":{"_route":"create_user","_controller":"App\\Controller\\UserController::createUser"},"request_uri":"http://localhost/users","method":"POST"} []
[2024-08-01T17:31:34.668019+02:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2024-08-01T17:31:34.701225+02:00] doctrine.INFO: Connecting with parameters array{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"symf_test","charset":"utf8mb4"} {"params":{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"symf_test","charset":"utf8mb4"}} []
[2024-08-01T17:31:34.708117+02:00] doctrine.INFO: Connecting with parameters array{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"charset":"utf8mb4"} {"params":{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"charset":"utf8mb4"}} []
[2024-08-01T17:31:34.714827+02:00] doctrine.INFO: Disconnecting [] []
[2024-08-01T17:31:34.721404+02:00] doctrine.INFO: Connecting with parameters array{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"symf_test","charset":"utf8mb4"} {"params":{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"symf_test","charset":"utf8mb4"}} []
[2024-08-01T17:31:34.767296+02:00] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ConnectionException: "An exception occurred in the driver: SQLSTATE[HY000] [1049] Unknown database 'symf_test'" at C:\Users\Arman Saleem\Desktop\symfony\users-service\vendor\doctrine\dbal\src\Driver\API\MySQL\ExceptionConverter.php line 101 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 1049): An exception occurred in the driver: SQLSTATE[HY000] [1049] Unknown database 'symf_test' at C:\\Users\\Arman Saleem\\Desktop\\symfony\\users-service\\vendor\\doctrine\\dbal\\src\\Driver\\API\\MySQL\\ExceptionConverter.php:101)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'symf_test' at C:\\Users\\Arman Saleem\\Desktop\\symfony\\users-service\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Exception.php:28)\n[previous exception] [object] (PDOException(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'symf_test' at C:\\Users\\Arman Saleem\\Desktop\\symfony\\users-service\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\MySQL\\Driver.php:33)"} []
[2024-08-01T17:32:02.457761+02:00] request.INFO: Matched route "create_user". {"route":"create_user","route_parameters":{"_route":"create_user","_controller":"App\\Controller\\UserController::createUser"},"request_uri":"http://localhost/users","method":"POST"} []
[2024-08-01T17:32:02.484842+02:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2024-08-01T17:32:02.508849+02:00] doctrine.INFO: Connecting with parameters array{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"symf_test","charset":"utf8mb4"} {"params":{"use_savepoints":true,"dbname_suffix":"_test","driver":"pdo_mysql","host":"127.0.0.1","port":3306,"user":"root","password":null,"driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"symf_test","charset":"utf8mb4"}} []
[2024-08-01T17:32:02.527638+02:00] doctrine.DEBUG: Beginning transaction [] []
[2024-08-01T17:32:02.554190+02:00] doctrine.DEBUG: Executing statement: INSERT INTO user (email, first_name, last_name) VALUES (?, ?, ?) (parameters: array{"1":"test@example.com","2":"John","3":"Doe"}, types: array{"1":2,"2":2,"3":2}) {"sql":"INSERT INTO user (email, first_name, last_name) VALUES (?, ?, ?)","params":{"1":"test@example.com","2":"John","3":"Doe"},"types":{"1":2,"2":2,"3":2}} []
[2024-08-01T17:32:02.558718+02:00] doctrine.DEBUG: Rolling back transaction [] []
[2024-08-01T17:32:02.589846+02:00] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\TableNotFoundException: "An exception occurred while executing a query: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'symf_test.user' doesn't exist" at C:\Users\Arman Saleem\Desktop\symfony\users-service\vendor\doctrine\dbal\src\Driver\API\MySQL\ExceptionConverter.php line 49 {"exception":"[object] (Doctrine\\DBAL\\Exception\\TableNotFoundException(code: 1146): An exception occurred while executing a query: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'symf_test.user' doesn't exist at C:\\Users\\Arman Saleem\\Desktop\\symfony\\users-service\\vendor\\doctrine\\dbal\\src\\Driver\\API\\MySQL\\ExceptionConverter.php:49)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1146): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'symf_test.user' doesn't exist at C:\\Users\\Arman Saleem\\Desktop\\symfony\\users-service\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Exception.php:28)\n[previous exception] [object] (PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'symf_test.user' doesn't exist at C:\\Users\\Arman Saleem\\Desktop\\symfony\\users-service\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Statement.php:130)"} []
